version: "3"
services:
  sonarqube:
    image: sonarqube:community #imagen de contenedor, se encuentra en docker hub imagen:tag o version
    depends_on:
      - db
    environment: #Variables de entorno
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar 
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes: #Para crear espacio carpetas dentro del contenedor
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports: # Puerto por defecto es 9000:9000 o 9001:9001
      - "9000:9000"
  db: # Base de datos
    image: postgres:12 #Imagen
    environment: #Variables de entorno
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes: #Volumenes que docker va a crear
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: